eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: http://discoveryserver:9001/eureka/
    instance:
        prefer-ip-address: true
server:
    port: 9011
spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
                    lower-case-service-id: true
    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: http://localhost:8082/realms/spring-boot-microservices-realm
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
