eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://discoveryserver:9001/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 9011
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - filters:
            - RemoveRequestHeader=Cookie
            - StripPrefix=1
          id: inventory-service
          predicates:
            - Path=/inventory-service/api/**
            - Method=GET,POST,PUT,DELETE
          uri: lb://inventory-service
        - filters:
            - RemoveRequestHeader=Cookie
            - StripPrefix=1
          id: filter-service
          predicates:
            - Path=/filter-service/api/**
            - Method=GET,POST,PUT,DELETE
          uri: lb://filter-service
        - filters:
            - RemoveRequestHeader=Cookie
            - StripPrefix=1
          id: invoice-service
          predicates:
            - Path=/invoice-service/api/**
            - Method=GET,POST,PUT,DELETE
          uri: lb://invoice-service
        - filters:
            - RemoveRequestHeader=Cookie
            - StripPrefix=1
          id: payment-service
          predicates:
            - Path=/payment-service/api/**
            - Method=GET,POST,PUT,DELETE
          uri: lb://payment-service
        - filters:
            - RemoveRequestHeader=Cookie
            - StripPrefix=1
          id: rental-service
          predicates: 
            - Path=/rental-service/api/**
            - Method=GET,POST,PUT,DELETE
          uri: lb://rental-service
      discovery:
        locator:
          enabled: true

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
